### ISSUE TITLE
The specific flickr subsets(20M and 10M) are encountering errors while trying to download all images. Getting PIL.UnidentifiedImageError: cannot identify image file error and execution stopping!

### ISSUE THREAD

**Issue by subhobose** [senthilps8/continuous_ssl_problem#5]

**Comment by johnson111788** [comment]
Same here. I have tried using different numbers of workers but it still won't work.

If possible, could the authors update the code or simply provide the images?

Best,
Yu-Cheng

```
(flickrCC) ychou11@ccvl25:/data/yucheng/LLL/Reference/continuous_ssl_problem/datasets/flickrCC$ python download_subset.py --root_dir /mnt/ccvl15/yucheng/LLL/Reference/continuous_ssl_problem/datasets/lists --subset lists/flickr-20M.tsv.gz --workers 2
0/10000000 images downloaded!
[2023-12-11T17:29:25.875-0500] {requester.py:79} WARNING - Unable to request URL: https://live.staticflickr.com/2260/2308818586_1580c1c129_b.jpg  Status code: 410
0/10000000 images downloaded!
[2023-12-11T17:29:31.882-0500] {requester.py:79} WARNING - Unable to request URL: https://live.staticflickr.com/81/214976826_2337203d61.jpg  Status code: 404
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/data/yucheng/anaconda3/envs/flickrCC/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/data/yucheng/anaconda3/envs/flickrCC/lib/python3.10/multiprocessing/pool.py", line 48, in mapstar
    return list(map(*args))
  File "/mnt/ccvl15/yucheng/LLL/Reference/continuous_ssl_problem/datasets/flickrCC/download_subset.py", line 44, in download_chunk
    download_and_resize(req, image_url, image_fn, RESIZE)
  File "/mnt/ccvl15/yucheng/LLL/Reference/continuous_ssl_problem/datasets/flickrCC/download_subset.py", line 22, in download_and_resize
    img = Image.open(BytesIO(req.get(url).content))
  File "/data/yucheng/anaconda3/envs/flickrCC/lib/python3.10/site-packages/PIL/Image.py", line 3305, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f18f9cce340>
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/ccvl15/yucheng/LLL/Reference/continuous_ssl_problem/datasets/flickrCC/download_subset.py", line 81, in <module>
    main()
  File "/mnt/ccvl15/yucheng/LLL/Reference/continuous_ssl_problem/datasets/flickrCC/download_subset.py", line 77, in main
    download_images(args.root_dir, args.subset, workers=args.workers)
  File "/mnt/ccvl15/yucheng/LLL/Reference/continuous_ssl_problem/datasets/flickrCC/download_subset.py", line 66, in download_images
    pool.map(download_fcn, image_chunks)
  File "/data/yucheng/anaconda3/envs/flickrCC/lib/python3.10/multiprocessing/pool.py", line 367, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/data/yucheng/anaconda3/envs/flickrCC/lib/python3.10/multiprocessing/pool.py", line 774, in get
    raise self._value
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f18f9cce340>
```

**Comment by senthilps8** [comment]
Unfortunately we cannot release the images because we don't have the rights to distribute them.
I think this issue is occurring due to a deleted or corrupted image.

I would suggest skipping these images by using a try-except block here:
https://github.com/senthilps8/continuous_ssl_problem/blob/942fa0f03318962903ec0aabd74568a1f902a628/datasets/flickrCC/download_subset.py#L22

Hopefully this would only skip a negligible number of images and not affect the results.
